steps:

- id: install
  name: 'gcr.io/cloud-builders/npm'
  args: ['install']

- id: build-server
  name: 'gcr.io/cloud-builders/npm'
  args: ['run','gas']
  env:
    - 'NODE_ENV=production'

- id: build-client
  name: 'gcr.io/cloud-builders/npm'
  args: ['run','prod']
  env:
    - 'NODE_ENV=production'

- id: push
  name: 'gcr.io/$PROJECT_ID/clasp'
  args: ['push','-f']
  env:
    - 'CLASPRC=$_CLASPRC'
    - 'SCRIPT_ID=$_SCRIPT_ID'
    - 'PROJECT_ID=$PROJECT_ID'
    - 'ROOT_DIR=./dist/gas'

- id: deploy
  name: 'gcr.io/$PROJECT_ID/clasp'
  args: ['deploy']
  env:
    - 'CLASPRC=$_CLASPRC'
    - 'SCRIPT_ID=$_SCRIPT_ID'
    - 'PROJECT_ID=$PROJECT_ID'
    - 'ROOT_DIR=./dist/gas'

substitutions:
  _CLASPRC: 'your clasp rc file in your home dir after logging in locally'
  _SCRIPT_ID: 'your script id of the apps script project to deploy to'
